### ISSUE TITLE
debug poly set to true on default

### ISSUE THREAD

**Issue by the-game-stoner** [BayloraiEX/bd-burgershot#2]
--STORAGE--
exports['qb-target']:AddBoxZone("BurgerShotBackStorage", vector3(-1196.51, -901.45, 14.0), 0.9, 0.9, {
	name = "BurgerShotBackStorage",
	heading = 347.27,
	debugPoly = true,
	minZ = 14.0 - 2,
	maxZ = 14.0 + 2,
},

should probably be set to false =) 
again i really like this script great job !

**Comment by BayloraiEX** [comment]
appreciate you finding these xD. Glad you like the script!
